---
- name: Download the artifact
  maven_artifact:
    group_id: in.shan5a6 
    artifact_id: myweb
    repository_url: 'http://35.88.194.166/repository/app3-artifacts'
    extension: war
    version: "{{ artifact_version }}"  
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    dest: /opt/tomcat/webapps/ 

- name: restart tomcat
  systemd:
    name: tomcat-service
    state: restarted  
